dubbo:
  application:
    name: repo-service
  scan:
    base-packages: com.pd.repo.impl
  config-center:
    address: zookeeper://192.168.2.112:2181?backup=192.168.2.113:2181,192.168.2.114:2181
  protocol:
    port: 20882