
dubbo:
  config-center:
    address: zookeeper://192.168.2.112:2181?backup=192.168.2.113:2181,192.168.2.114:2181
  application:
    name: pay-service
  scan:
    base-packages: com.pd.pay.impl
  protocol:
    port: 20881